packages:
  - "packages/*"

catalog:
  "@radix-ui/react-checkbox": "^1.1.4"
  "@radix-ui/react-dropdown-menu": "^2.1.6"
  "@radix-ui/react-tabs": "^1.1.3"
  "@tanstack/react-table": "^8.21.2"
  "@prisma/client": "^7.2.0"
  "prisma": "^7.2.0"
  "class-variance-authority": "^0.7.1"
  "clsx": "^2.1.1"
  "lucide-react": "^0.483.0"
  "next": "^16.1.0-canary.12"
  "next-themes": "^0.4.6"
  "react": "19.2.3"
  "react-dom": "19.2.3"
  "sonner": "^2.0.7"
  "tailwind-merge": "^3.0.2"
  "vaul": "^1.1.2"
  "zod": "^3.24.2"
  "framer-motion": "^12.0.11"
  "@radix-ui/react-dialog": "^1.1.6"
  "@radix-ui/react-select": "^2.1.6"
  "@radix-ui/react-slot": "^1.1.2"
  "@radix-ui/react-tooltip": "^1.1.8"
  "@tailwindcss/postcss": "^4"
  "@types/node": "^20.17.25"
  "@types/react": "19.2.2"
  "@types/react-dom": "19.2.2"
  "tailwindcss": "^4"
  "tsx": "^4.19.3"
  "typescript": "^5.8.2"
